# Generated by Django 2.2.3 on 2019-07-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20190705_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('title', models.CharField(choices=[('01', '곡물/견과류'), ('02', '채소'), ('03', '과일'), ('04', '해산물'), ('05', '육류/기타')], max_length=2)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
